/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateOrderLineRequest', function() {
      beforeEach(function() {
        instance = new PblmRestApi.CreateOrderLineRequest();
      });

      it('should create an instance of CreateOrderLineRequest', function() {
        // TODO: update the code to test CreateOrderLineRequest
        expect(instance).to.be.a(PblmRestApi.CreateOrderLineRequest);
      });

      it('should have the property ordreId (base name: "ordre_id")', function() {
        // TODO: update the code to test the property ordreId
        expect(instance).to.have.property('ordreId');
        // expect(instance.ordreId).to.be(expectedValueLiteral);
      });

      it('should have the property varenr (base name: "varenr")', function() {
        // TODO: update the code to test the property varenr
        expect(instance).to.have.property('varenr');
        // expect(instance.varenr).to.be(expectedValueLiteral);
      });

      it('should have the property antal (base name: "antal")', function() {
        // TODO: update the code to test the property antal
        expect(instance).to.have.property('antal');
        // expect(instance.antal).to.be(expectedValueLiteral);
      });

      it('should have the property pris (base name: "pris")', function() {
        // TODO: update the code to test the property pris
        expect(instance).to.have.property('pris');
        // expect(instance.pris).to.be(expectedValueLiteral);
      });

      it('should have the property rabat (base name: "rabat")', function() {
        // TODO: update the code to test the property rabat
        expect(instance).to.have.property('rabat');
        // expect(instance.rabat).to.be(expectedValueLiteral);
      });

      it('should have the property beskrivelse (base name: "beskrivelse")', function() {
        // TODO: update the code to test the property beskrivelse
        expect(instance).to.have.property('beskrivelse');
        // expect(instance.beskrivelse).to.be(expectedValueLiteral);
      });

      it('should have the property momsfri (base name: "momsfri")', function() {
        // TODO: update the code to test the property momsfri
        expect(instance).to.have.property('momsfri');
        // expect(instance.momsfri).to.be(expectedValueLiteral);
      });

      it('should have the property procent (base name: "procent")', function() {
        // TODO: update the code to test the property procent
        expect(instance).to.have.property('procent');
        // expect(instance.procent).to.be(expectedValueLiteral);
      });

    });
  });

}));
