/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateProductRequestSize', function() {
      beforeEach(function() {
        instance = new PblmRestApi.CreateProductRequestSize();
      });

      it('should create an instance of CreateProductRequestSize', function() {
        // TODO: update the code to test CreateProductRequestSize
        expect(instance).to.be.a(PblmRestApi.CreateProductRequestSize);
      });

      it('should have the property width (base name: "width")', function() {
        // TODO: update the code to test the property width
        expect(instance).to.have.property('width');
        // expect(instance.width).to.be(expectedValueLiteral);
      });

      it('should have the property height (base name: "height")', function() {
        // TODO: update the code to test the property height
        expect(instance).to.have.property('height');
        // expect(instance.height).to.be(expectedValueLiteral);
      });

      it('should have the property length (base name: "length")', function() {
        // TODO: update the code to test the property length
        expect(instance).to.have.property('length');
        // expect(instance.length).to.be(expectedValueLiteral);
      });

      it('should have the property netWeight (base name: "netWeight")', function() {
        // TODO: update the code to test the property netWeight
        expect(instance).to.have.property('netWeight');
        // expect(instance.netWeight).to.be(expectedValueLiteral);
      });

      it('should have the property grossWeight (base name: "grossWeight")', function() {
        // TODO: update the code to test the property grossWeight
        expect(instance).to.have.property('grossWeight');
        // expect(instance.grossWeight).to.be(expectedValueLiteral);
      });

    });
  });

}));
