/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateProductRequestSize model module.
 * @module model/CreateProductRequestSize
 * @version 1.0.0
 */
export default class CreateProductRequestSize {
  /**
   * Constructs a new <code>CreateProductRequestSize</code>.
   * @alias module:model/CreateProductRequestSize
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateProductRequestSize</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateProductRequestSize} obj Optional instance to populate.
   * @return {module:model/CreateProductRequestSize} The populated <code>CreateProductRequestSize</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateProductRequestSize();
      if (data.hasOwnProperty('width'))
        obj.width = ApiClient.convertToType(data['width'], 'Number');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('length'))
        obj.length = ApiClient.convertToType(data['length'], 'Number');
      if (data.hasOwnProperty('netWeight'))
        obj.netWeight = ApiClient.convertToType(data['netWeight'], 'Number');
      if (data.hasOwnProperty('grossWeight'))
        obj.grossWeight = ApiClient.convertToType(data['grossWeight'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} width
 */
CreateProductRequestSize.prototype.width = undefined;

/**
 * @member {Number} height
 */
CreateProductRequestSize.prototype.height = undefined;

/**
 * @member {Number} length
 */
CreateProductRequestSize.prototype.length = undefined;

/**
 * @member {Number} netWeight
 */
CreateProductRequestSize.prototype.netWeight = undefined;

/**
 * @member {Number} grossWeight
 */
CreateProductRequestSize.prototype.grossWeight = undefined;

