/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateCreditorGroupRequest model module.
 * @module model/CreateCreditorGroupRequest
 * @version 1.0.0
 */
export default class CreateCreditorGroupRequest {
  /**
   * Constructs a new <code>CreateCreditorGroupRequest</code>.
   * @alias module:model/CreateCreditorGroupRequest
   * @class
   * @param description {String} Group description
   * @param vatGroup {String} VAT group
   * @param currency {String} Currency code
   * @param language {String} Language code
   */
  constructor(description, vatGroup, currency, language) {
    this.description = description;
    this.vatGroup = vatGroup;
    this.currency = currency;
    this.language = language;
  }

  /**
   * Constructs a <code>CreateCreditorGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCreditorGroupRequest} obj Optional instance to populate.
   * @return {module:model/CreateCreditorGroupRequest} The populated <code>CreateCreditorGroupRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateCreditorGroupRequest();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('vatGroup'))
        obj.vatGroup = ApiClient.convertToType(data['vatGroup'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('contraAccount'))
        obj.contraAccount = ApiClient.convertToType(data['contraAccount'], 'String');
      if (data.hasOwnProperty('reversePayment'))
        obj.reversePayment = ApiClient.convertToType(data['reversePayment'], 'Boolean');
      if (data.hasOwnProperty('b2b'))
        obj.b2b = ApiClient.convertToType(data['b2b'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Group description
 * @member {String} description
 */
CreateCreditorGroupRequest.prototype.description = undefined;

/**
 * VAT group
 * @member {String} vatGroup
 */
CreateCreditorGroupRequest.prototype.vatGroup = undefined;

/**
 * Currency code
 * @member {String} currency
 */
CreateCreditorGroupRequest.prototype.currency = undefined;

/**
 * Language code
 * @member {String} language
 */
CreateCreditorGroupRequest.prototype.language = undefined;

/**
 * Contra account
 * @member {String} contraAccount
 */
CreateCreditorGroupRequest.prototype.contraAccount = undefined;

/**
 * Reverse payment flag
 * @member {Boolean} reversePayment
 */
CreateCreditorGroupRequest.prototype.reversePayment = undefined;

/**
 * B2B flag
 * @member {Boolean} b2b
 */
CreateCreditorGroupRequest.prototype.b2b = undefined;

