/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CreateProductRequestSize from './CreateProductRequestSize';

/**
 * The CreateProductRequest model module.
 * @module model/CreateProductRequest
 * @version 1.0.0
 */
export default class CreateProductRequest {
  /**
   * Constructs a new <code>CreateProductRequest</code>.
   * @alias module:model/CreateProductRequest
   * @class
   * @param varenr {String} Product number
   */
  constructor(varenr) {
    this.varenr = varenr;
  }

  /**
   * Constructs a <code>CreateProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateProductRequest} obj Optional instance to populate.
   * @return {module:model/CreateProductRequest} The populated <code>CreateProductRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateProductRequest();
      if (data.hasOwnProperty('varenr'))
        obj.varenr = ApiClient.convertToType(data['varenr'], 'String');
      if (data.hasOwnProperty('stregkode'))
        obj.stregkode = ApiClient.convertToType(data['stregkode'], 'String');
      if (data.hasOwnProperty('beskrivelse'))
        obj.beskrivelse = ApiClient.convertToType(data['beskrivelse'], 'String');
      if (data.hasOwnProperty('salgspris'))
        obj.salgspris = ApiClient.convertToType(data['salgspris'], 'Number');
      if (data.hasOwnProperty('kostpris'))
        obj.kostpris = ApiClient.convertToType(data['kostpris'], 'Number');
      if (data.hasOwnProperty('size'))
        obj.size = CreateProductRequestSize.constructFromObject(data['size']);
    }
    return obj;
  }
}

/**
 * Product number
 * @member {String} varenr
 */
CreateProductRequest.prototype.varenr = undefined;

/**
 * Barcode
 * @member {String} stregkode
 */
CreateProductRequest.prototype.stregkode = undefined;

/**
 * Description
 * @member {String} beskrivelse
 */
CreateProductRequest.prototype.beskrivelse = undefined;

/**
 * Sales price
 * @member {Number} salgspris
 */
CreateProductRequest.prototype.salgspris = undefined;

/**
 * Cost price
 * @member {Number} kostpris
 */
CreateProductRequest.prototype.kostpris = undefined;

/**
 * @member {module:model/CreateProductRequestSize} size
 */
CreateProductRequest.prototype.size = undefined;

