/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateOrderLineRequest model module.
 * @module model/CreateOrderLineRequest
 * @version 1.0.0
 */
export default class CreateOrderLineRequest {
  /**
   * Constructs a new <code>CreateOrderLineRequest</code>.
   * @alias module:model/CreateOrderLineRequest
   * @class
   * @param ordreId {Number} Order ID
   */
  constructor(ordreId) {
    this.ordreId = ordreId;
  }

  /**
   * Constructs a <code>CreateOrderLineRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateOrderLineRequest} obj Optional instance to populate.
   * @return {module:model/CreateOrderLineRequest} The populated <code>CreateOrderLineRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateOrderLineRequest();
      if (data.hasOwnProperty('ordre_id'))
        obj.ordreId = ApiClient.convertToType(data['ordre_id'], 'Number');
      if (data.hasOwnProperty('varenr'))
        obj.varenr = ApiClient.convertToType(data['varenr'], 'String');
      if (data.hasOwnProperty('antal'))
        obj.antal = ApiClient.convertToType(data['antal'], 'Number');
      if (data.hasOwnProperty('pris'))
        obj.pris = ApiClient.convertToType(data['pris'], 'Number');
      if (data.hasOwnProperty('rabat'))
        obj.rabat = ApiClient.convertToType(data['rabat'], 'Number');
      if (data.hasOwnProperty('beskrivelse'))
        obj.beskrivelse = ApiClient.convertToType(data['beskrivelse'], 'String');
      if (data.hasOwnProperty('momsfri'))
        obj.momsfri = ApiClient.convertToType(data['momsfri'], 'Number');
      if (data.hasOwnProperty('procent'))
        obj.procent = ApiClient.convertToType(data['procent'], 'Number');
    }
    return obj;
  }
}

/**
 * Order ID
 * @member {Number} ordreId
 */
CreateOrderLineRequest.prototype.ordreId = undefined;

/**
 * Product number
 * @member {String} varenr
 */
CreateOrderLineRequest.prototype.varenr = undefined;

/**
 * Quantity
 * @member {Number} antal
 */
CreateOrderLineRequest.prototype.antal = undefined;

/**
 * Price
 * @member {Number} pris
 */
CreateOrderLineRequest.prototype.pris = undefined;

/**
 * Discount
 * @member {Number} rabat
 */
CreateOrderLineRequest.prototype.rabat = undefined;

/**
 * Description
 * @member {String} beskrivelse
 */
CreateOrderLineRequest.prototype.beskrivelse = undefined;

/**
 * VAT exempt flag
 * @member {Number} momsfri
 */
CreateOrderLineRequest.prototype.momsfri = undefined;

/**
 * Percentage
 * @member {Number} procent
 */
CreateOrderLineRequest.prototype.procent = undefined;

