/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateOrderRequest model module.
 * @module model/CreateOrderRequest
 * @version 1.0.0
 */
export default class CreateOrderRequest {
  /**
   * Constructs a new <code>CreateOrderRequest</code>.
   * @alias module:model/CreateOrderRequest
   * @class
   * @param firmanavn {String} Company name
   * @param telefon {String} Phone number
   * @param email {String} Email address
   * @param momssats {Number} VAT rate
   */
  constructor(firmanavn, telefon, email, momssats) {
    this.firmanavn = firmanavn;
    this.telefon = telefon;
    this.email = email;
    this.momssats = momssats;
  }

  /**
   * Constructs a <code>CreateOrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateOrderRequest} obj Optional instance to populate.
   * @return {module:model/CreateOrderRequest} The populated <code>CreateOrderRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateOrderRequest();
      if (data.hasOwnProperty('firmanavn'))
        obj.firmanavn = ApiClient.convertToType(data['firmanavn'], 'String');
      if (data.hasOwnProperty('telefon'))
        obj.telefon = ApiClient.convertToType(data['telefon'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('momssats'))
        obj.momssats = ApiClient.convertToType(data['momssats'], 'Number');
      if (data.hasOwnProperty('sum'))
        obj.sum = ApiClient.convertToType(data['sum'], 'Number');
      if (data.hasOwnProperty('kostpris'))
        obj.kostpris = ApiClient.convertToType(data['kostpris'], 'Number');
      if (data.hasOwnProperty('moms'))
        obj.moms = ApiClient.convertToType(data['moms'], 'Number');
      if (data.hasOwnProperty('valuta'))
        obj.valuta = ApiClient.convertToType(data['valuta'], 'String');
      if (data.hasOwnProperty('betalingsbet'))
        obj.betalingsbet = ApiClient.convertToType(data['betalingsbet'], 'String');
      if (data.hasOwnProperty('betalingsdage'))
        obj.betalingsdage = ApiClient.convertToType(data['betalingsdage'], 'Number');
      if (data.hasOwnProperty('addr1'))
        obj.addr1 = ApiClient.convertToType(data['addr1'], 'String');
      if (data.hasOwnProperty('addr2'))
        obj.addr2 = ApiClient.convertToType(data['addr2'], 'String');
      if (data.hasOwnProperty('postnr'))
        obj.postnr = ApiClient.convertToType(data['postnr'], 'String');
      if (data.hasOwnProperty('bynavn'))
        obj.bynavn = ApiClient.convertToType(data['bynavn'], 'String');
      if (data.hasOwnProperty('land'))
        obj.land = ApiClient.convertToType(data['land'], 'String');
      if (data.hasOwnProperty('lev_navn'))
        obj.levNavn = ApiClient.convertToType(data['lev_navn'], 'String');
      if (data.hasOwnProperty('lev_addr1'))
        obj.levAddr1 = ApiClient.convertToType(data['lev_addr1'], 'String');
      if (data.hasOwnProperty('lev_addr2'))
        obj.levAddr2 = ApiClient.convertToType(data['lev_addr2'], 'String');
      if (data.hasOwnProperty('lev_postnr'))
        obj.levPostnr = ApiClient.convertToType(data['lev_postnr'], 'String');
      if (data.hasOwnProperty('lev_bynavn'))
        obj.levBynavn = ApiClient.convertToType(data['lev_bynavn'], 'String');
      if (data.hasOwnProperty('lev_land'))
        obj.levLand = ApiClient.convertToType(data['lev_land'], 'String');
      if (data.hasOwnProperty('ean'))
        obj.ean = ApiClient.convertToType(data['ean'], 'String');
      if (data.hasOwnProperty('cvrnr'))
        obj.cvrnr = ApiClient.convertToType(data['cvrnr'], 'String');
      if (data.hasOwnProperty('ordredate'))
        obj.ordredate = ApiClient.convertToType(data['ordredate'], 'Date');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
      if (data.hasOwnProperty('betalt'))
        obj.betalt = ApiClient.convertToType(data['betalt'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Company name
 * @member {String} firmanavn
 */
CreateOrderRequest.prototype.firmanavn = undefined;

/**
 * Phone number
 * @member {String} telefon
 */
CreateOrderRequest.prototype.telefon = undefined;

/**
 * Email address
 * @member {String} email
 */
CreateOrderRequest.prototype.email = undefined;

/**
 * VAT rate
 * @member {Number} momssats
 */
CreateOrderRequest.prototype.momssats = undefined;

/**
 * Order total
 * @member {Number} sum
 */
CreateOrderRequest.prototype.sum = undefined;

/**
 * Cost price
 * @member {Number} kostpris
 */
CreateOrderRequest.prototype.kostpris = undefined;

/**
 * VAT amount
 * @member {Number} moms
 */
CreateOrderRequest.prototype.moms = undefined;

/**
 * Currency code
 * @member {String} valuta
 */
CreateOrderRequest.prototype.valuta = undefined;

/**
 * Payment terms
 * @member {String} betalingsbet
 */
CreateOrderRequest.prototype.betalingsbet = undefined;

/**
 * Payment days
 * @member {Number} betalingsdage
 */
CreateOrderRequest.prototype.betalingsdage = undefined;

/**
 * Address line 1
 * @member {String} addr1
 */
CreateOrderRequest.prototype.addr1 = undefined;

/**
 * Address line 2
 * @member {String} addr2
 */
CreateOrderRequest.prototype.addr2 = undefined;

/**
 * Postal code
 * @member {String} postnr
 */
CreateOrderRequest.prototype.postnr = undefined;

/**
 * City name
 * @member {String} bynavn
 */
CreateOrderRequest.prototype.bynavn = undefined;

/**
 * Country
 * @member {String} land
 */
CreateOrderRequest.prototype.land = undefined;

/**
 * Delivery name
 * @member {String} levNavn
 */
CreateOrderRequest.prototype.levNavn = undefined;

/**
 * Delivery address 1
 * @member {String} levAddr1
 */
CreateOrderRequest.prototype.levAddr1 = undefined;

/**
 * Delivery address 2
 * @member {String} levAddr2
 */
CreateOrderRequest.prototype.levAddr2 = undefined;

/**
 * Delivery postal code
 * @member {String} levPostnr
 */
CreateOrderRequest.prototype.levPostnr = undefined;

/**
 * Delivery city
 * @member {String} levBynavn
 */
CreateOrderRequest.prototype.levBynavn = undefined;

/**
 * Delivery country
 * @member {String} levLand
 */
CreateOrderRequest.prototype.levLand = undefined;

/**
 * EAN number
 * @member {String} ean
 */
CreateOrderRequest.prototype.ean = undefined;

/**
 * CVR number
 * @member {String} cvrnr
 */
CreateOrderRequest.prototype.cvrnr = undefined;

/**
 * Order date
 * @member {Date} ordredate
 */
CreateOrderRequest.prototype.ordredate = undefined;

/**
 * Notes
 * @member {String} notes
 */
CreateOrderRequest.prototype.notes = undefined;

/**
 * Paid status
 * @member {Boolean} betalt
 */
CreateOrderRequest.prototype.betalt = undefined;

