/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateCustomerRequest model module.
 * @module model/CreateCustomerRequest
 * @version 1.0.0
 */
export default class CreateCustomerRequest {
  /**
   * Constructs a new <code>CreateCustomerRequest</code>.
   * @alias module:model/CreateCustomerRequest
   * @class
   * @param firmanavn {String} Company name
   * @param tlf {String} Phone number
   * @param email {String} Email address
   */
  constructor(firmanavn, tlf, email) {
    this.firmanavn = firmanavn;
    this.tlf = tlf;
    this.email = email;
  }

  /**
   * Constructs a <code>CreateCustomerRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCustomerRequest} obj Optional instance to populate.
   * @return {module:model/CreateCustomerRequest} The populated <code>CreateCustomerRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateCustomerRequest();
      if (data.hasOwnProperty('firmanavn'))
        obj.firmanavn = ApiClient.convertToType(data['firmanavn'], 'String');
      if (data.hasOwnProperty('tlf'))
        obj.tlf = ApiClient.convertToType(data['tlf'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('addr1'))
        obj.addr1 = ApiClient.convertToType(data['addr1'], 'String');
      if (data.hasOwnProperty('addr2'))
        obj.addr2 = ApiClient.convertToType(data['addr2'], 'String');
      if (data.hasOwnProperty('postnr'))
        obj.postnr = ApiClient.convertToType(data['postnr'], 'String');
      if (data.hasOwnProperty('bynavn'))
        obj.bynavn = ApiClient.convertToType(data['bynavn'], 'String');
      if (data.hasOwnProperty('cvrnr'))
        obj.cvrnr = ApiClient.convertToType(data['cvrnr'], 'String');
      if (data.hasOwnProperty('land'))
        obj.land = ApiClient.convertToType(data['land'], 'String');
      if (data.hasOwnProperty('bank_navn'))
        obj.bankNavn = ApiClient.convertToType(data['bank_navn'], 'String');
      if (data.hasOwnProperty('bank_reg'))
        obj.bankReg = ApiClient.convertToType(data['bank_reg'], 'String');
      if (data.hasOwnProperty('bank_konto'))
        obj.bankKonto = ApiClient.convertToType(data['bank_konto'], 'String');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
      if (data.hasOwnProperty('betalingsbet'))
        obj.betalingsbet = ApiClient.convertToType(data['betalingsbet'], 'String');
      if (data.hasOwnProperty('betalingsdage'))
        obj.betalingsdage = ApiClient.convertToType(data['betalingsdage'], 'Number');
      if (data.hasOwnProperty('ean'))
        obj.ean = ApiClient.convertToType(data['ean'], 'String');
      if (data.hasOwnProperty('fornavn'))
        obj.fornavn = ApiClient.convertToType(data['fornavn'], 'String');
      if (data.hasOwnProperty('efternavn'))
        obj.efternavn = ApiClient.convertToType(data['efternavn'], 'String');
    }
    return obj;
  }
}

/**
 * Company name
 * @member {String} firmanavn
 */
CreateCustomerRequest.prototype.firmanavn = undefined;

/**
 * Phone number
 * @member {String} tlf
 */
CreateCustomerRequest.prototype.tlf = undefined;

/**
 * Email address
 * @member {String} email
 */
CreateCustomerRequest.prototype.email = undefined;

/**
 * Address line 1
 * @member {String} addr1
 */
CreateCustomerRequest.prototype.addr1 = undefined;

/**
 * Address line 2
 * @member {String} addr2
 */
CreateCustomerRequest.prototype.addr2 = undefined;

/**
 * Postal code
 * @member {String} postnr
 */
CreateCustomerRequest.prototype.postnr = undefined;

/**
 * City name
 * @member {String} bynavn
 */
CreateCustomerRequest.prototype.bynavn = undefined;

/**
 * CVR number
 * @member {String} cvrnr
 */
CreateCustomerRequest.prototype.cvrnr = undefined;

/**
 * Country
 * @member {String} land
 */
CreateCustomerRequest.prototype.land = undefined;

/**
 * Bank name
 * @member {String} bankNavn
 */
CreateCustomerRequest.prototype.bankNavn = undefined;

/**
 * Bank registration
 * @member {String} bankReg
 */
CreateCustomerRequest.prototype.bankReg = undefined;

/**
 * Bank account
 * @member {String} bankKonto
 */
CreateCustomerRequest.prototype.bankKonto = undefined;

/**
 * Notes
 * @member {String} notes
 */
CreateCustomerRequest.prototype.notes = undefined;

/**
 * Payment terms
 * @member {String} betalingsbet
 */
CreateCustomerRequest.prototype.betalingsbet = undefined;

/**
 * Payment days
 * @member {Number} betalingsdage
 */
CreateCustomerRequest.prototype.betalingsdage = undefined;

/**
 * EAN number
 * @member {String} ean
 */
CreateCustomerRequest.prototype.ean = undefined;

/**
 * First name
 * @member {String} fornavn
 */
CreateCustomerRequest.prototype.fornavn = undefined;

/**
 * Last name
 * @member {String} efternavn
 */
CreateCustomerRequest.prototype.efternavn = undefined;

