/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateVatRequest model module.
 * @module model/CreateVatRequest
 * @version 1.0.0
 */
export default class CreateVatRequest {
  /**
   * Constructs a new <code>CreateVatRequest</code>.
   * @alias module:model/CreateVatRequest
   * @class
   * @param momskode {String} VAT code
   * @param nr {Number} Number
   * @param beskrivelse {String} Description
   * @param account {String} Account number
   * @param sats {Number} VAT rate
   */
  constructor(momskode, nr, beskrivelse, account, sats) {
    this.momskode = momskode;
    this.nr = nr;
    this.beskrivelse = beskrivelse;
    this.account = account;
    this.sats = sats;
  }

  /**
   * Constructs a <code>CreateVatRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateVatRequest} obj Optional instance to populate.
   * @return {module:model/CreateVatRequest} The populated <code>CreateVatRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateVatRequest();
      if (data.hasOwnProperty('momskode'))
        obj.momskode = ApiClient.convertToType(data['momskode'], 'String');
      if (data.hasOwnProperty('nr'))
        obj.nr = ApiClient.convertToType(data['nr'], 'Number');
      if (data.hasOwnProperty('beskrivelse'))
        obj.beskrivelse = ApiClient.convertToType(data['beskrivelse'], 'String');
      if (data.hasOwnProperty('account'))
        obj.account = ApiClient.convertToType(data['account'], 'String');
      if (data.hasOwnProperty('sats'))
        obj.sats = ApiClient.convertToType(data['sats'], 'Number');
      if (data.hasOwnProperty('modkonto'))
        obj.modkonto = ApiClient.convertToType(data['modkonto'], 'String');
      if (data.hasOwnProperty('map'))
        obj.map = ApiClient.convertToType(data['map'], 'String');
    }
    return obj;
  }
}

/**
 * VAT code
 * @member {String} momskode
 */
CreateVatRequest.prototype.momskode = undefined;

/**
 * Number
 * @member {Number} nr
 */
CreateVatRequest.prototype.nr = undefined;

/**
 * Description
 * @member {String} beskrivelse
 */
CreateVatRequest.prototype.beskrivelse = undefined;

/**
 * Account number
 * @member {String} account
 */
CreateVatRequest.prototype.account = undefined;

/**
 * VAT rate
 * @member {Number} sats
 */
CreateVatRequest.prototype.sats = undefined;

/**
 * Contra account
 * @member {String} modkonto
 */
CreateVatRequest.prototype.modkonto = undefined;

/**
 * Map reference
 * @member {String} map
 */
CreateVatRequest.prototype.map = undefined;

