/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreditorGroupResponse model module.
 * @module model/CreditorGroupResponse
 * @version 1.0.0
 */
export default class CreditorGroupResponse {
  /**
   * Constructs a new <code>CreditorGroupResponse</code>.
   * @alias module:model/CreditorGroupResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreditorGroupResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreditorGroupResponse} obj Optional instance to populate.
   * @return {module:model/CreditorGroupResponse} The populated <code>CreditorGroupResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreditorGroupResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('vatGroup'))
        obj.vatGroup = ApiClient.convertToType(data['vatGroup'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('contraAccount'))
        obj.contraAccount = ApiClient.convertToType(data['contraAccount'], 'String');
      if (data.hasOwnProperty('reversePayment'))
        obj.reversePayment = ApiClient.convertToType(data['reversePayment'], 'Boolean');
      if (data.hasOwnProperty('b2b'))
        obj.b2b = ApiClient.convertToType(data['b2b'], 'Boolean');
      if (data.hasOwnProperty('kodenr'))
        obj.kodenr = ApiClient.convertToType(data['kodenr'], 'Number');
      if (data.hasOwnProperty('fiscal_year'))
        obj.fiscalYear = ApiClient.convertToType(data['fiscal_year'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CreditorGroupResponse.prototype.id = undefined;

/**
 * @member {String} description
 */
CreditorGroupResponse.prototype.description = undefined;

/**
 * @member {String} vatGroup
 */
CreditorGroupResponse.prototype.vatGroup = undefined;

/**
 * @member {String} currency
 */
CreditorGroupResponse.prototype.currency = undefined;

/**
 * @member {String} language
 */
CreditorGroupResponse.prototype.language = undefined;

/**
 * @member {String} contraAccount
 */
CreditorGroupResponse.prototype.contraAccount = undefined;

/**
 * @member {Boolean} reversePayment
 */
CreditorGroupResponse.prototype.reversePayment = undefined;

/**
 * @member {Boolean} b2b
 */
CreditorGroupResponse.prototype.b2b = undefined;

/**
 * @member {Number} kodenr
 */
CreditorGroupResponse.prototype.kodenr = undefined;

/**
 * @member {Number} fiscalYear
 */
CreditorGroupResponse.prototype.fiscalYear = undefined;

