/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CurrencyResponse model module.
 * @module model/CurrencyResponse
 * @version 1.0.0
 */
export default class CurrencyResponse {
  /**
   * Constructs a new <code>CurrencyResponse</code>.
   * @alias module:model/CurrencyResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CurrencyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CurrencyResponse} obj Optional instance to populate.
   * @return {module:model/CurrencyResponse} The populated <code>CurrencyResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CurrencyResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('beskrivelse'))
        obj.beskrivelse = ApiClient.convertToType(data['beskrivelse'], 'String');
      if (data.hasOwnProperty('currencyCode'))
        obj.currencyCode = ApiClient.convertToType(data['currencyCode'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CurrencyResponse.prototype.id = undefined;

/**
 * @member {String} beskrivelse
 */
CurrencyResponse.prototype.beskrivelse = undefined;

/**
 * @member {String} currencyCode
 */
CurrencyResponse.prototype.currencyCode = undefined;

