/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CustomerResponse model module.
 * @module model/CustomerResponse
 * @version 1.0.0
 */
export default class CustomerResponse {
  /**
   * Constructs a new <code>CustomerResponse</code>.
   * @alias module:model/CustomerResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CustomerResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerResponse} obj Optional instance to populate.
   * @return {module:model/CustomerResponse} The populated <code>CustomerResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CustomerResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('firmanavn'))
        obj.firmanavn = ApiClient.convertToType(data['firmanavn'], 'String');
      if (data.hasOwnProperty('tlf'))
        obj.tlf = ApiClient.convertToType(data['tlf'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('addr1'))
        obj.addr1 = ApiClient.convertToType(data['addr1'], 'String');
      if (data.hasOwnProperty('addr2'))
        obj.addr2 = ApiClient.convertToType(data['addr2'], 'String');
      if (data.hasOwnProperty('postnr'))
        obj.postnr = ApiClient.convertToType(data['postnr'], 'String');
      if (data.hasOwnProperty('bynavn'))
        obj.bynavn = ApiClient.convertToType(data['bynavn'], 'String');
      if (data.hasOwnProperty('cvrnr'))
        obj.cvrnr = ApiClient.convertToType(data['cvrnr'], 'String');
      if (data.hasOwnProperty('land'))
        obj.land = ApiClient.convertToType(data['land'], 'String');
      if (data.hasOwnProperty('art'))
        obj.art = ApiClient.convertToType(data['art'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CustomerResponse.prototype.id = undefined;

/**
 * @member {String} firmanavn
 */
CustomerResponse.prototype.firmanavn = undefined;

/**
 * @member {String} tlf
 */
CustomerResponse.prototype.tlf = undefined;

/**
 * @member {String} email
 */
CustomerResponse.prototype.email = undefined;

/**
 * @member {String} addr1
 */
CustomerResponse.prototype.addr1 = undefined;

/**
 * @member {String} addr2
 */
CustomerResponse.prototype.addr2 = undefined;

/**
 * @member {String} postnr
 */
CustomerResponse.prototype.postnr = undefined;

/**
 * @member {String} bynavn
 */
CustomerResponse.prototype.bynavn = undefined;

/**
 * @member {String} cvrnr
 */
CustomerResponse.prototype.cvrnr = undefined;

/**
 * @member {String} land
 */
CustomerResponse.prototype.land = undefined;

/**
 * @member {String} art
 */
CustomerResponse.prototype.art = undefined;

