/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderLineResponse model module.
 * @module model/OrderLineResponse
 * @version 1.0.0
 */
export default class OrderLineResponse {
  /**
   * Constructs a new <code>OrderLineResponse</code>.
   * @alias module:model/OrderLineResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderLineResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderLineResponse} obj Optional instance to populate.
   * @return {module:model/OrderLineResponse} The populated <code>OrderLineResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderLineResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('ordre_id'))
        obj.ordreId = ApiClient.convertToType(data['ordre_id'], 'Number');
      if (data.hasOwnProperty('vare_id'))
        obj.vareId = ApiClient.convertToType(data['vare_id'], 'Number');
      if (data.hasOwnProperty('varenr'))
        obj.varenr = ApiClient.convertToType(data['varenr'], 'String');
      if (data.hasOwnProperty('beskrivelse'))
        obj.beskrivelse = ApiClient.convertToType(data['beskrivelse'], 'String');
      if (data.hasOwnProperty('antal'))
        obj.antal = ApiClient.convertToType(data['antal'], 'Number');
      if (data.hasOwnProperty('pris'))
        obj.pris = ApiClient.convertToType(data['pris'], 'Number');
      if (data.hasOwnProperty('rabat'))
        obj.rabat = ApiClient.convertToType(data['rabat'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
OrderLineResponse.prototype.id = undefined;

/**
 * @member {Number} ordreId
 */
OrderLineResponse.prototype.ordreId = undefined;

/**
 * @member {Number} vareId
 */
OrderLineResponse.prototype.vareId = undefined;

/**
 * @member {String} varenr
 */
OrderLineResponse.prototype.varenr = undefined;

/**
 * @member {String} beskrivelse
 */
OrderLineResponse.prototype.beskrivelse = undefined;

/**
 * @member {Number} antal
 */
OrderLineResponse.prototype.antal = undefined;

/**
 * @member {Number} pris
 */
OrderLineResponse.prototype.pris = undefined;

/**
 * @member {Number} rabat
 */
OrderLineResponse.prototype.rabat = undefined;

