/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderResponse model module.
 * @module model/OrderResponse
 * @version 1.0.0
 */
export default class OrderResponse {
  /**
   * Constructs a new <code>OrderResponse</code>.
   * @alias module:model/OrderResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderResponse} obj Optional instance to populate.
   * @return {module:model/OrderResponse} The populated <code>OrderResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('ordrenr'))
        obj.ordrenr = ApiClient.convertToType(data['ordrenr'], 'Number');
      if (data.hasOwnProperty('firmanavn'))
        obj.firmanavn = ApiClient.convertToType(data['firmanavn'], 'String');
      if (data.hasOwnProperty('telefon'))
        obj.telefon = ApiClient.convertToType(data['telefon'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('momssats'))
        obj.momssats = ApiClient.convertToType(data['momssats'], 'Number');
      if (data.hasOwnProperty('sum'))
        obj.sum = ApiClient.convertToType(data['sum'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
      if (data.hasOwnProperty('ordredate'))
        obj.ordredate = ApiClient.convertToType(data['ordredate'], 'Date');
      if (data.hasOwnProperty('valuta'))
        obj.valuta = ApiClient.convertToType(data['valuta'], 'String');
      if (data.hasOwnProperty('ref'))
        obj.ref = ApiClient.convertToType(data['ref'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
OrderResponse.prototype.id = undefined;

/**
 * @member {Number} ordrenr
 */
OrderResponse.prototype.ordrenr = undefined;

/**
 * @member {String} firmanavn
 */
OrderResponse.prototype.firmanavn = undefined;

/**
 * @member {String} telefon
 */
OrderResponse.prototype.telefon = undefined;

/**
 * @member {String} email
 */
OrderResponse.prototype.email = undefined;

/**
 * @member {Number} momssats
 */
OrderResponse.prototype.momssats = undefined;

/**
 * @member {Number} sum
 */
OrderResponse.prototype.sum = undefined;

/**
 * @member {Number} status
 */
OrderResponse.prototype.status = undefined;

/**
 * @member {Date} ordredate
 */
OrderResponse.prototype.ordredate = undefined;

/**
 * @member {String} valuta
 */
OrderResponse.prototype.valuta = undefined;

/**
 * @member {String} ref
 */
OrderResponse.prototype.ref = undefined;

