/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ProductResponse from './ProductResponse';

/**
 * The ProductListResponse model module.
 * @module model/ProductListResponse
 * @version 1.0.0
 */
export default class ProductListResponse {
  /**
   * Constructs a new <code>ProductListResponse</code>.
   * @alias module:model/ProductListResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductListResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductListResponse} obj Optional instance to populate.
   * @return {module:model/ProductListResponse} The populated <code>ProductListResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductListResponse();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [ProductResponse]);
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
ProductListResponse.prototype.success = undefined;

/**
 * @member {Array.<module:model/ProductResponse>} data
 */
ProductListResponse.prototype.data = undefined;

