/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductResponse model module.
 * @module model/ProductResponse
 * @version 1.0.0
 */
export default class ProductResponse {
  /**
   * Constructs a new <code>ProductResponse</code>.
   * @alias module:model/ProductResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductResponse} obj Optional instance to populate.
   * @return {module:model/ProductResponse} The populated <code>ProductResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('varenr'))
        obj.varenr = ApiClient.convertToType(data['varenr'], 'String');
      if (data.hasOwnProperty('stregkode'))
        obj.stregkode = ApiClient.convertToType(data['stregkode'], 'String');
      if (data.hasOwnProperty('beskrivelse'))
        obj.beskrivelse = ApiClient.convertToType(data['beskrivelse'], 'String');
      if (data.hasOwnProperty('salgspris'))
        obj.salgspris = ApiClient.convertToType(data['salgspris'], 'Number');
      if (data.hasOwnProperty('kostpris'))
        obj.kostpris = ApiClient.convertToType(data['kostpris'], 'Number');
      if (data.hasOwnProperty('modtime'))
        obj.modtime = ApiClient.convertToType(data['modtime'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ProductResponse.prototype.id = undefined;

/**
 * @member {String} varenr
 */
ProductResponse.prototype.varenr = undefined;

/**
 * @member {String} stregkode
 */
ProductResponse.prototype.stregkode = undefined;

/**
 * @member {String} beskrivelse
 */
ProductResponse.prototype.beskrivelse = undefined;

/**
 * @member {Number} salgspris
 */
ProductResponse.prototype.salgspris = undefined;

/**
 * @member {Number} kostpris
 */
ProductResponse.prototype.kostpris = undefined;

/**
 * @member {Date} modtime
 */
ProductResponse.prototype.modtime = undefined;

