/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CreateCreditorGroupRequest from './CreateCreditorGroupRequest';

/**
 * The UpdateCreditorGroupRequest model module.
 * @module model/UpdateCreditorGroupRequest
 * @version 1.0.0
 */
export default class UpdateCreditorGroupRequest extends CreateCreditorGroupRequest {
  /**
   * Constructs a new <code>UpdateCreditorGroupRequest</code>.
   * @alias module:model/UpdateCreditorGroupRequest
   * @class
   * @extends module:model/CreateCreditorGroupRequest
   * @param description {} Group description
   * @param vatGroup {} VAT group
   * @param currency {} Currency code
   * @param language {} Language code
   */
  constructor(description, vatGroup, currency, language) {
    super(description, vatGroup, currency, language);
  }

  /**
   * Constructs a <code>UpdateCreditorGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateCreditorGroupRequest} obj Optional instance to populate.
   * @return {module:model/UpdateCreditorGroupRequest} The populated <code>UpdateCreditorGroupRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateCreditorGroupRequest();
      CreateCreditorGroupRequest.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * Creditor group ID
 * @member {Number} id
 */
UpdateCreditorGroupRequest.prototype.id = undefined;

