/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CreateDebitorGroupRequest from './CreateDebitorGroupRequest';

/**
 * The UpdateDebitorGroupRequest model module.
 * @module model/UpdateDebitorGroupRequest
 * @version 1.0.0
 */
export default class UpdateDebitorGroupRequest extends CreateDebitorGroupRequest {
  /**
   * Constructs a new <code>UpdateDebitorGroupRequest</code>.
   * @alias module:model/UpdateDebitorGroupRequest
   * @class
   * @extends module:model/CreateDebitorGroupRequest
   * @param description {} Group description
   * @param vatGroup {} VAT group
   * @param currency {} Currency code
   * @param language {} Language code
   */
  constructor(description, vatGroup, currency, language) {
    super(description, vatGroup, currency, language);
  }

  /**
   * Constructs a <code>UpdateDebitorGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateDebitorGroupRequest} obj Optional instance to populate.
   * @return {module:model/UpdateDebitorGroupRequest} The populated <code>UpdateDebitorGroupRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateDebitorGroupRequest();
      CreateDebitorGroupRequest.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * Debitor group ID
 * @member {Number} id
 */
UpdateDebitorGroupRequest.prototype.id = undefined;

