/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CreateVatRequest from './CreateVatRequest';

/**
 * The UpdateVatRequest model module.
 * @module model/UpdateVatRequest
 * @version 1.0.0
 */
export default class UpdateVatRequest extends CreateVatRequest {
  /**
   * Constructs a new <code>UpdateVatRequest</code>.
   * @alias module:model/UpdateVatRequest
   * @class
   * @extends module:model/CreateVatRequest
   * @param momskode {} VAT code
   * @param nr {} Number
   * @param beskrivelse {} Description
   * @param account {} Account number
   * @param sats {} VAT rate
   */
  constructor(momskode, nr, beskrivelse, account, sats) {
    super(momskode, nr, beskrivelse, account, sats);
  }

  /**
   * Constructs a <code>UpdateVatRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateVatRequest} obj Optional instance to populate.
   * @return {module:model/UpdateVatRequest} The populated <code>UpdateVatRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateVatRequest();
      CreateVatRequest.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * VAT item ID
 * @member {Number} id
 */
UpdateVatRequest.prototype.id = undefined;

