/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CreateProductRequest from './CreateProductRequest';
import CreateProductRequestSize from './CreateProductRequestSize';

/**
 * The UpdateProductRequest model module.
 * @module model/UpdateProductRequest
 * @version 1.0.0
 */
export default class UpdateProductRequest extends CreateProductRequest {
  /**
   * Constructs a new <code>UpdateProductRequest</code>.
   * @alias module:model/UpdateProductRequest
   * @class
   * @extends module:model/CreateProductRequest
   * @param id {} Product ID
   * @param varenr {} Product number
   */
  constructor(id, varenr) {
    super(varenr);
    this.id = id;
  }

  /**
   * Constructs a <code>UpdateProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateProductRequest} obj Optional instance to populate.
   * @return {module:model/UpdateProductRequest} The populated <code>UpdateProductRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateProductRequest();
      CreateProductRequest.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * Product ID
 * @member {Number} id
 */
UpdateProductRequest.prototype.id = undefined;

