/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The VatResponse model module.
 * @module model/VatResponse
 * @version 1.0.0
 */
export default class VatResponse {
  /**
   * Constructs a new <code>VatResponse</code>.
   * @alias module:model/VatResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>VatResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VatResponse} obj Optional instance to populate.
   * @return {module:model/VatResponse} The populated <code>VatResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VatResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('momskode'))
        obj.momskode = ApiClient.convertToType(data['momskode'], 'String');
      if (data.hasOwnProperty('nr'))
        obj.nr = ApiClient.convertToType(data['nr'], 'Number');
      if (data.hasOwnProperty('beskrivelse'))
        obj.beskrivelse = ApiClient.convertToType(data['beskrivelse'], 'String');
      if (data.hasOwnProperty('fiscal_year'))
        obj.fiscalYear = ApiClient.convertToType(data['fiscal_year'], 'Number');
      if (data.hasOwnProperty('account'))
        obj.account = ApiClient.convertToType(data['account'], 'String');
      if (data.hasOwnProperty('sats'))
        obj.sats = ApiClient.convertToType(data['sats'], 'Number');
      if (data.hasOwnProperty('modkonto'))
        obj.modkonto = ApiClient.convertToType(data['modkonto'], 'String');
      if (data.hasOwnProperty('map'))
        obj.map = ApiClient.convertToType(data['map'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
VatResponse.prototype.id = undefined;

/**
 * @member {String} momskode
 */
VatResponse.prototype.momskode = undefined;

/**
 * @member {Number} nr
 */
VatResponse.prototype.nr = undefined;

/**
 * @member {String} beskrivelse
 */
VatResponse.prototype.beskrivelse = undefined;

/**
 * @member {Number} fiscalYear
 */
VatResponse.prototype.fiscalYear = undefined;

/**
 * @member {String} account
 */
VatResponse.prototype.account = undefined;

/**
 * @member {Number} sats
 */
VatResponse.prototype.sats = undefined;

/**
 * @member {String} modkonto
 */
VatResponse.prototype.modkonto = undefined;

/**
 * @member {String} map
 */
VatResponse.prototype.map = undefined;

