#!/bin/bash
set -e

# Detect the owner of the mounted volume
TARGET_UID=$(stat -c "%u" /var/www/html/saldi)
TARGET_GID=$(stat -c "%g" /var/www/html/saldi)

echo "Adjusting www-data to execute with UID: $TARGET_UID and GID: $TARGET_GID"

# Change www-data's uid and gid to match the host user
usermod -u "$TARGET_UID" -o www-data
groupmod -g "$TARGET_GID" -o www-data

# Ensure www-data owns the named volumes (temp dirs)
# Even with UID match, named volumes might be owned by root initially.
chown -R www-data:www-data /var/www/html/saldi/temp \
                         /var/www/html/saldi/includes/temp \
                         /var/www/html/saldi/bordplaner/temp \
                         /var/www/html/saldi/logolib

# --- Auto-generate connect.php when GENERATE_CONNECT_PHP=1 ---
if [ "$GENERATE_CONNECT_PHP" = "1" ]; the# Always regenerate to ensure connect.php matches current env vars
n
    echo "Regenerating connect.php from environment variables..."

    if [ ! -z "$DB_HOST" ] && [ ! -z "$DB_USER" ] && [ ! -z "$DB_PASSWORD" ] && [ ! -z "$DB_NAME" ]; then
        echo "Writing new includes/connect.php..."
        
        DB_TYPE=${DB_TYPE:-postgresql}
        DB_ENCODE=${DB_ENCODE:-UTF8}
        
        cat <<EOF > /var/www/html/saldi/includes/connect.php
<?php
// Auto-generated by entrypoint.sTilføjede DEBIAN_FRONTEND=noninteractive for ikke-interaktive apt-kørsler.h

if (!isset(\$bg)) \$bg='';
if (!isset(\$title)) \$title='';
\$db_encode = "$DB_ENCODE";
\$db_type = "$DB_TYPE";

if (file_exists("../includes/db_query.php")) {
	include("../includes/db_query.php");
	include("../includes/version.php");
	include("../includes/settings.php");
}
elseif (file_exists("../../includes/db_query.php")){
	include("../../includes/db_query.php");
	include("../../includes/version.php");
	include("../../includes/settings.php");
}

\$sqhost = "$DB_HOST";
\$squser = "$DB_USER";
\$sqpass = "$DB_PASSWORD";
\$sqdb   = "$DB_NAME";

\$login = "cookie";
\$revisorregnskab = "1";

\$font = "<font face='Arial, Helvetica, sans-serif'>";

if (!function_exists('saldi_redirect_to_install')) {
	function saldi_redirect_to_install() {
		\$url = "/index/install.php";

		// CLI: redirect to web installer
		if (PHP_SAPI === 'cli') {
			fwrite(STDERR, "SALDI not initialized. Open \$url in browser to run installer.\\n");
			exit(1);
		}

		if (!headers_sent()) {
			header("Cache-Control: no-store");
			header("Location: \$url");
		}
		echo "<meta http-equiv=\\"refresh\\" content=\\"0;URL=\$url\\">";
		exit;
	}
}
EOF

        # Append the PHP logic using quoted heredoc (PREVENTS BASH EXPANSION)
        if [ "$DB_TYPE" = "mysqli" ]; then
            cat <<'EOF' >> /var/www/html/saldi/includes/connect.php

$connection = db_connect ("$sqhost", "$squser", "$sqpass");
if (!$connection) saldi_redirect_to_install();

if (!mysqli_select_db($connection, $sqdb)) saldi_redirect_to_install();
mysqli_query($connection, "SET SESSION default_storage_engine='InnoDB'");

// Basic schema check (prevents hard failures before installer can run)
$saldi_schema_check = mysqli_query(
	$connection,
	"SELECT COUNT(*) AS cnt FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name IN ('regnskab','settings')"
);
if (!$saldi_schema_check) saldi_redirect_to_install();
$saldi_schema_row = mysqli_fetch_assoc($saldi_schema_check);
if ((int)($saldi_schema_row['cnt'] ?? 0) < 2) saldi_redirect_to_install();
EOF
        else
            cat <<'EOF' >> /var/www/html/saldi/includes/connect.php

if ($sqpass) $connection = db_connect ("$sqhost", "$squser", "$sqpass", "$sqdb");
else $connection = db_connect ("$sqhost", "$squser", "$sqpass", "$sqdb");

if (!$connection) saldi_redirect_to_install();

// Basic schema check (prevents hard failures before installer can run)
$saldi_schema_check = pg_query($connection, "SELECT to_regclass('public.regnskab') AS regnskab, to_regclass('public.settings') AS settings");
if (!$saldi_schema_check) saldi_redirect_to_install();
$saldi_schema_row = pg_fetch_assoc($saldi_schema_check);
if (empty($saldi_schema_row['regnskab']) || empty($saldi_schema_row['settings'])) saldi_redirect_to_install();
EOF
        fi

        echo "?>" >> /var/www/html/saldi/includes/connect.php

        chown www-data:www-data /var/www/html/saldi/includes/connect.php
        echo "connect.php generated successfully."
    else
        echo "Environment variables DB_HOST, DB_USER, DB_PASSWORD, DB_NAME not fully set. Skipping auto-generation."
    fi
else
    echo "GENERATE_CONNECT_PHP not set to 1. Skipping connect.php generation."
fi
# ---------------------------------------------------------------------

# Execute the passed command
exec "$@"
