/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PblmRestApi.CreditorGroupsApi();
  });

  describe('(package)', function() {
    describe('CreditorGroupsApi', function() {
      describe('creditorGroupsGet', function() {
        it('should call creditorGroupsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for creditorGroupsGet call and complete the assertions
          /*
          var opts = {};

          instance.creditorGroupsGet(xDb, xSaldiuser, xApikey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CreditorGroupListResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('creditorGroupsIdDelete', function() {
        it('should call creditorGroupsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for creditorGroupsIdDelete call
          /*

          instance.creditorGroupsIdDelete(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('creditorGroupsIdGet', function() {
        it('should call creditorGroupsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for creditorGroupsIdGet call and complete the assertions
          /*

          instance.creditorGroupsIdGet(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CreditorGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('creditorGroupsIdPut', function() {
        it('should call creditorGroupsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for creditorGroupsIdPut call and complete the assertions
          /*

          instance.creditorGroupsIdPut(body, xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CreditorGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('creditorGroupsPost', function() {
        it('should call creditorGroupsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for creditorGroupsPost call and complete the assertions
          /*

          instance.creditorGroupsPost(body, xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CreditorGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
