/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PblmRestApi.CurrenciesApi();
  });

  describe('(package)', function() {
    describe('CurrenciesApi', function() {
      describe('currenciesDelete', function() {
        it('should call currenciesDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for currenciesDelete call
          /*

          instance.currenciesDelete(xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('currenciesGet', function() {
        it('should call currenciesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for currenciesGet call and complete the assertions
          /*
          var opts = {};

          instance.currenciesGet(xDb, xSaldiuser, xApikey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CurrencyListResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('currenciesIdGet', function() {
        it('should call currenciesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for currenciesIdGet call and complete the assertions
          /*

          instance.currenciesIdGet(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CurrencyResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('currenciesPost', function() {
        it('should call currenciesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for currenciesPost call
          /*

          instance.currenciesPost(xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('currenciesPut', function() {
        it('should call currenciesPut successfully', function(done) {
          // TODO: uncomment, update parameter values for currenciesPut call
          /*

          instance.currenciesPut(xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
