/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PblmRestApi.CustomersApi();
  });

  describe('(package)', function() {
    describe('CustomersApi', function() {
      describe('debitorCustomersGet', function() {
        it('should call debitorCustomersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorCustomersGet call and complete the assertions
          /*

          instance.debitorCustomersGet(xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CustomerListResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorCustomersIdDelete', function() {
        it('should call debitorCustomersIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorCustomersIdDelete call
          /*

          instance.debitorCustomersIdDelete(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorCustomersIdGet', function() {
        it('should call debitorCustomersIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorCustomersIdGet call and complete the assertions
          /*

          instance.debitorCustomersIdGet(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CustomerResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorCustomersIdPut', function() {
        it('should call debitorCustomersIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorCustomersIdPut call
          /*

          instance.debitorCustomersIdPut(body, xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorCustomersPost', function() {
        it('should call debitorCustomersPost successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorCustomersPost call and complete the assertions
          /*

          instance.debitorCustomersPost(body, xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.CustomerResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
