/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PblmRestApi.DebitorOrdersApi();
  });

  describe('(package)', function() {
    describe('DebitorOrdersApi', function() {
      describe('debitorOrdersGet', function() {
        it('should call debitorOrdersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorOrdersGet call and complete the assertions
          /*
          var opts = {};

          instance.debitorOrdersGet(xDb, xSaldiuser, xApikey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.OrderListResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorOrdersIdGet', function() {
        it('should call debitorOrdersIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorOrdersIdGet call and complete the assertions
          /*

          instance.debitorOrdersIdGet(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.OrderResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorOrdersPost', function() {
        it('should call debitorOrdersPost successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorOrdersPost call and complete the assertions
          /*

          instance.debitorOrdersPost(body, xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.OrderResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
