/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PblmRestApi.DebitorGroupsApi();
  });

  describe('(package)', function() {
    describe('DebitorGroupsApi', function() {
      describe('debitorGroupsGet', function() {
        it('should call debitorGroupsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorGroupsGet call and complete the assertions
          /*
          var opts = {};

          instance.debitorGroupsGet(xDb, xSaldiuser, xApikey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.DebitorGroupListResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorGroupsIdDelete', function() {
        it('should call debitorGroupsIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorGroupsIdDelete call
          /*

          instance.debitorGroupsIdDelete(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorGroupsIdGet', function() {
        it('should call debitorGroupsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorGroupsIdGet call and complete the assertions
          /*

          instance.debitorGroupsIdGet(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.DebitorGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorGroupsIdPut', function() {
        it('should call debitorGroupsIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorGroupsIdPut call and complete the assertions
          /*

          instance.debitorGroupsIdPut(body, xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.DebitorGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorGroupsPost', function() {
        it('should call debitorGroupsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorGroupsPost call and complete the assertions
          /*

          instance.debitorGroupsPost(body, xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.DebitorGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
