/*
 * PBLM REST API
 * A comprehensive REST API for managing orders, customers, products, inventory, VAT, groups, and currencies.  ## Authentication All endpoints require authentication via headers: - `x-db`: Database identifier - `x-saldiuser`: User identifier - `x-apikey`: API key for authentication 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PblmRestApi);
  }
}(this, function(expect, PblmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PblmRestApi.OrderLinesApi();
  });

  describe('(package)', function() {
    describe('OrderLinesApi', function() {
      describe('creditorOrderlinesGet', function() {
        it('should call creditorOrderlinesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for creditorOrderlinesGet call and complete the assertions
          /*

          instance.creditorOrderlinesGet(xDb, xSaldiuser, xApikey, orderId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.OrderLineListResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('creditorOrderlinesPost', function() {
        it('should call creditorOrderlinesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for creditorOrderlinesPost call
          /*

          instance.creditorOrderlinesPost(body, xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorOrderlinesGet', function() {
        it('should call debitorOrderlinesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorOrderlinesGet call and complete the assertions
          /*

          instance.debitorOrderlinesGet(xDb, xSaldiuser, xApikey, orderId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.OrderLineListResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorOrderlinesIdGet', function() {
        it('should call debitorOrderlinesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorOrderlinesIdGet call and complete the assertions
          /*

          instance.debitorOrderlinesIdGet(xDb, xSaldiuser, xApikey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.OrderLineResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('debitorOrderlinesPost', function() {
        it('should call debitorOrderlinesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for debitorOrderlinesPost call and complete the assertions
          /*

          instance.debitorOrderlinesPost(body, xDb, xSaldiuser, xApikey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PblmRestApi.OrderLineResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
