#!/usr/bin/env bash
#
# tools/ci/bootstrap-stack.sh - take a fresh clone to a testable installation.
#
# A clone of this repository cannot serve a single page: includes/connect.php
# is generated by the install wizard and is gitignored, and the test suites
# need a tenant to work against. Everything DB-backed in tests/ skips itself
# when that is missing, so a CI job that just runs PHPUnit on a fresh checkout
# reports "OK" while having exercised almost nothing.
#
# This script performs the two steps a human would do in the browser:
#
#   1. index/install.php  - writes includes/connect.php, creates the master
#                           database and the admin login.
#   2. admin/opret.php    - creates an accounting entity: its own database,
#                           ~116 tables, and the seed data from importfiler/.
#
# Both are single form posts. Step 2 needs no session, which is a defect in
# its own right - see doc/TESTING_FINDINGS.md P1-4 and
# tests/restapi/AdminOpretAuthorizationTest.php. This script does not rely on
# that: it posts as the administrator it just created. If the hole is closed,
# the login below keeps this working.
#
# Idempotent-ish: it refuses to run against a master database that already
# has accounting entities, so it cannot quietly wipe a working stack.
#
# Usage:  tools/ci/bootstrap-stack.sh
# Env:    SALDI_BASE_URL   (default http://localhost:5000/saldi)
#         SALDI_MASTER_DB  (default saldi)
#         SALDI_ACCOUNT    (default saldi_chatbot_test - what the e2e specs expect)
#         SALDI_ADMIN      (default admin)
#         SALDI_ADMIN_PW   (default a local-only literal)
#
# History:
# 20260725 CL/LH Created for the end-to-end coverage push.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

BASE_URL="${SALDI_BASE_URL:-http://localhost:5000/saldi}"
MASTER_DB="${SALDI_MASTER_DB:-saldi}"
ACCOUNT="${SALDI_ACCOUNT:-saldi_chatbot_test}"
ADMIN="${SALDI_ADMIN:-admin}"
ADMIN_PW="${SALDI_ADMIN_PW:-saldi-ci-local-2026}"

PG_USER="${SALDI_PGUSER:-user}"
PG_PASS="${SALDI_PGPASS:-password}"

say() { printf '\n== %s\n' "$1"; }

psql_master() {
  docker compose exec -T -e "PGPASSWORD=$PG_PASS" postgres \
    psql -v ON_ERROR_STOP=1 -U "$PG_USER" -d postgres -tAc "$1"
}

say "waiting for the stack"
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null "$BASE_URL/index/index.php" 2>/dev/null; then break; fi
  sleep 2
done

say "checking the master database is safe to (re)install"
existing="$(psql_master "SELECT 1 FROM pg_database WHERE datname='$MASTER_DB'" || true)"
if [ -n "$existing" ]; then
  entities="$(docker compose exec -T -e "PGPASSWORD=$PG_PASS" postgres \
    psql -U "$PG_USER" -d "$MASTER_DB" -tAc \
    "SELECT count(*) FROM regnskab WHERE db <> '$MASTER_DB'" 2>/dev/null || echo 0)"
  if [ "${entities:-0}" -gt 0 ]; then
    echo "refusing to reinstall: $MASTER_DB already has $entities accounting entities." >&2
    echo "This looks like a working stack, not a fresh CI runner." >&2
    exit 1
  fi
  # install.php aborts if the master database exists, and docker-compose
  # pre-creates an empty one.
  psql_master "DROP DATABASE IF EXISTS $MASTER_DB"
fi

say "step 1: install (creates includes/connect.php + the master database)"
# index/install.php redirects straight back out if includes/connect.php is
# already there (install.php:55), so a leftover file from an earlier attempt
# makes the wizard answer 200 and do nothing.
rm -f "$REPO_ROOT/includes/connect.php"
install_out="$(mktemp)"
curl -fsS -o "$install_out" \
  --data-urlencode "opret=1" \
  --data-urlencode "language=1" \
  --data-urlencode "db_type=postgresql" \
  --data-urlencode "db_encode=UTF8" \
  --data-urlencode "db_host=postgres" \
  --data-urlencode "db_navn=$MASTER_DB" \
  --data-urlencode "db_bruger=$PG_USER" \
  --data-urlencode "db_password=$PG_PASS" \
  --data-urlencode "adm_navn=$ADMIN" \
  --data-urlencode "adm_password=$ADMIN_PW" \
  --data-urlencode "verify_adm_password=$ADMIN_PW" \
  "$BASE_URL/index/install.php"

# Judge the install on what it was for - the master database - rather than on
# the config file, which the wizard writes before it does any of the work.
if [ ! -f "$REPO_ROOT/includes/connect.php" ] || [ -z "$(psql_master "SELECT 1 FROM pg_database WHERE datname='$MASTER_DB'")" ]; then
  echo "install did not complete; wizard said:" >&2
  sed -e 's/<[^>]*>//g' "$install_out" | grep -v '^\s*$' | head -30 >&2
  exit 1
fi
echo "connect.php written, master database $MASTER_DB created"

say "step 2: create the accounting entity '$ACCOUNT'"
cookies="$(mktemp)"
# Log in as the administrator we just created, so this works whether or not
# admin/opret.php still accepts unauthenticated posts.
curl -fsS -o /dev/null -c "$cookies" -b "$cookies" \
  --data-urlencode "regnskab=$MASTER_DB" \
  --data-urlencode "brugernavn=$ADMIN" \
  --data-urlencode "password=$ADMIN_PW" \
  "$BASE_URL/index/index.php" || true

opret_out="$(mktemp)"
curl -fsS -o "$opret_out" -c "$cookies" -b "$cookies" \
  --max-time 900 \
  --data-urlencode "regnskab=$ACCOUNT" \
  --data-urlencode "brugernavn=$ADMIN" \
  --data-urlencode "passwd=$ADMIN_PW" \
  --data-urlencode "passwd2=$ADMIN_PW" \
  --data-urlencode "std_kto_plan=1" \
  "$BASE_URL/admin/opret.php"

tenant_db="$(docker compose exec -T -e "PGPASSWORD=$PG_PASS" postgres \
  psql -U "$PG_USER" -d "$MASTER_DB" -tAc \
  "SELECT db FROM regnskab WHERE regnskab='$ACCOUNT' LIMIT 1" | tr -d '[:space:]')"

if [ -z "$tenant_db" ]; then
  echo "the accounting entity was not created; page said:" >&2
  sed -e 's/<[^>]*>//g' "$opret_out" | grep -v '^\s*$' | head -30 >&2
  exit 1
fi

tables="$(docker compose exec -T -e "PGPASSWORD=$PG_PASS" postgres \
  psql -U "$PG_USER" -d "$tenant_db" -tAc \
  "SELECT count(*) FROM information_schema.tables WHERE table_schema='public'" | tr -d '[:space:]')"

if [ "${tables:-0}" -lt 50 ]; then
  echo "tenant $tenant_db has only $tables tables - the schema did not install" >&2
  exit 1
fi

say "done"
echo "  master database : $MASTER_DB"
echo "  accounting entity: $ACCOUNT ($tenant_db, $tables tables)"
echo
echo "The suites default to SALDI_CHAR_TEMPLATE_DB=$tenant_db; export it if you"
echo "used a different SALDI_ACCOUNT."
