<?php
// Start output buffering FIRST to capture any output from includes
ob_start();

// Start session and set environment
@session_start();
$s_id = session_id();
$header = 'nix';  // Suppress header output
$bg = 'nix';      // Suppress body output
$title = 'docPoolData';

// Prevent caching of this JSON response to ensure fresh file list
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

// Include database connection and online.php to get $db
include_once(__DIR__ . "/connect.php");
include_once(__DIR__ . "/std_func.php");

// Get $db from session/online table
$qtxt = "select db from online where session_id = '$s_id' order by logtime desc limit 1";
$r = db_fetch_array(db_select($qtxt, __FILE__ . " line " . __LINE__));
$db = $r['db'] ?? '';

// Connect to the correct database
if ($db) {
    global $sqhost, $squser, $sqpass;
    $connection = db_connect($sqhost, $squser, $sqpass, $db, __FILE__ . " line " . __LINE__);
}

// Clean any output generated by includes
while (ob_get_level()) {
    ob_end_clean();
}
ob_start();

$dir = $_GET['dir'] ?? null;
$params = isset($_GET['params']) ? urldecode($_GET['params']) : '';
$poolParams = isset($_GET['poolParams']) ? urldecode($_GET['poolParams']) : '';

// Database-only mode: Get all files from pool_files table
$data = [];
$fil_nr = 0;

// Query all files from the pool_files table (database is the source of truth)
$qtxt = "SELECT filename, subject, account, amount, file_date, invoice_number, description 
         FROM pool_files ORDER BY file_date DESC, updated DESC";
$result = db_select($qtxt, __FILE__ . " line " . __LINE__);

while ($row = db_fetch_array($result)) {
    $file = $row['filename'];
    $base = pathinfo($file, PATHINFO_FILENAME);
    
    $subject = $row['subject'] ?: $base;
    $account = $row['account'] ?: '';
    $amount = $row['amount'] ?: '';
    $modDate = $row['file_date'] ?: '';
    $invoiceNumber = $row['invoice_number'] ?: '';
    $description = $row['description'] ?: '';
    
    $fil_nr++;
    
    // Build href - remove any existing poolFile from poolParams
    $cleanPoolParams = preg_replace('/&?poolFile=[^&]*/', '', $poolParams);
    $cleanPoolParams = ltrim($cleanPoolParams, '&');
    $hreftxt = "../includes/documents.php?$params&$cleanPoolParams&docFocus=$fil_nr&poolFile=" . urlencode($file);
    
    $data[] = [
        'filename' => $file,
        'subject' => $subject,
        'account' => $account,
        'amount' => $amount,
        'date' => $modDate,
        'href' => $hreftxt,
        'invoiceNumber' => $invoiceNumber,
        'description' => $description,
        'fil_nr' => $fil_nr,
    ];
}

// Clear any previous output and send proper JSON
ob_end_clean();
header('Content-Type: application/json');

echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

exit;
