<?php
//                ___   _   _   ___  _     ___  _ _
//               / __| / \ | | |   \| |   |   \| / /
//               \__ \/ _ \| |_| |) | | _ | |) |  <
//               |___/_/ \_|___|___/|_||_||___/|_\_\
//
// --- includes/_docPoolData.php --- ver 5.0.0 --- 2026-10-01 ---
// LICENSE
//
// This program is free software. You can redistribute it and / or
// modify it under the terms of the GNU General Public License (GPL)
// which is published by The Free Software Foundation; either in version 2
// of this license or later version of your choice.
// However, respect the following:
//
// It is forbidden to use this program in competition with Saldi.DK ApS
// or other proprietor of the program without prior written agreement.
//
// The program is published with the hope that it will be beneficial,
// but WITHOUT ANY KIND OF CLAIM OR WARRANTY.
// See GNU General Public License for more details.
// http://www.saldi.dk/dok/GNU_GPL_v2.html
//
// Copyright (c) 2025-2026 Danosoft ApS
// ----------------------------------------------------------------------
// 20260914 CDX/LH Expose metadata versions and manual acceptance for document-pool editing.
// 20260922 CL/LAH Leverandørforslag fra AI-scan: every file now carries a 'vendor' object
//                  (see poolVendorMatcher.php / kravspec afsnit 5) or null, and files with
//                  vendor identity but no kreditor are matched again on every open (AI-6).
// 20260922 CL/LAH Vendor handling wrapped so it can never break the file list; invalid UTF-8
//                  from legacy rows is substituted instead of blanking the whole response.
// 20260925 LOE MB-42 Every row whose fakturanr, amount and date match another row's is marked
//                  duplicateOf, so the pool can show that the same bilag is in the list twice.
// 20261001 CL/NTR Merged the two history blocks into one and grouped the includes.

// Start output buffering FIRST to capture any output from includes
ob_start();

// Start session and set environment
@session_start();
$s_id = session_id();
$header = 'nix';  // Suppress header output
$bg = 'nix';      // Suppress body output
$title = 'docPoolData';

// Prevent caching of this JSON response to ensure fresh file list
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

// Include database connection and online.php to get $db
include_once(__DIR__ . "/connect.php");
include_once(__DIR__ . "/std_func.php");
include_once(__DIR__ . "/docsIncludes/poolVendorMatcher.php");
include_once(__DIR__ . "/docsIncludes/poolDuplicateMarker.php");
require_once __DIR__ . '/docsIncludes/poolMetadata.php';

// Get $db from session/online table
$qtxt = "select db from online where session_id = '$s_id' order by logtime desc limit 1";
$r = db_fetch_array(db_select($qtxt, __FILE__ . " line " . __LINE__));
$db = $r['db'] ?? '';

// Connect to the correct database
if ($db) {
    global $sqhost, $squser, $sqpass;
    $connection = db_connect($sqhost, $squser, $sqpass, $db, __FILE__ . " line " . __LINE__);
}

// Clean any output generated by includes
while (ob_get_level()) {
    ob_end_clean();
}
ob_start();

$dir = $_GET['dir'] ?? null;
$params = isset($_GET['params']) ? urldecode($_GET['params']) : '';
$poolParams = isset($_GET['poolParams']) ? urldecode($_GET['poolParams']) : '';

// Database-only mode: Get all files from pool_files table
$data = [];
$fil_nr = 0;

// Kreditor index for the vendor contract (one query, reused for every file). Built lazily
// so a tenant whose betweenUpdates.php has not yet added the vendor_* columns costs nothing.
$vendorIndex = null;
$vendorColumnsExist = poolVendorColumnsExist();

// Query all files from the pool_files table (database is the source of truth)
$vendorSelect = $vendorColumnsExist ? ", vendor_name, vendor_cvr, vendor_iban, vendor_konto_id, vendor_match, vendor_score" : "";
$qtxt = "SELECT id, filename, subject, account, amount, file_date, invoice_number, description, currency, updated, manually_edited$vendorSelect
         FROM pool_files ORDER BY file_date DESC, updated DESC";
$result = db_select($qtxt, __FILE__ . " line " . __LINE__);

while ($row = db_fetch_array($result)) {
    $file = $row['filename'];
    $base = pathinfo($file, PATHINFO_FILENAME);
    
    $subject = $row['subject'] ?: $base;
    $account = $row['account'] ?: '';
    $amount = $row['amount'] ?? '';
    $modDate = $row['file_date'] ?: '';
    $invoiceNumber = $row['invoice_number'] ?: '';
    $description = $row['description'] ?: '';
    $currency = $row['currency'] ?: '';

    // Vendor contract (kravspec afsnit 5), null for files scanned before vendor support.
    $vendor = null;
    if ($vendorColumnsExist && trim((string) ($row['vendor_match'] ?? '')) !== '') {
        try {
            if ($vendorIndex === null) $vendorIndex = poolVendorLoadIndex();
            if (poolVendorNeedsRematch($row, $vendorIndex)) {
                // AI-6: the kreditor may have been created (or deleted) after the scan. Pure
                // lookups against the index already in memory - no extra queries per file
                // beyond the UPDATE when the outcome changed.
                $bank = poolVendorRowFromIban($row['vendor_iban'] ?? null);
                $fresh = poolVendorMatch(array(
                    'name' => $row['vendor_name'] ?? null,
                    'cvr' => $row['vendor_cvr'] ?? null,
                    'iban' => $bank['iban'],
                    'bank_reg' => $bank['bank_reg'],
                    'bank_konto' => $bank['bank_konto'],
                ), $vendorIndex, array('nameScan' => 'tokens'));
                $storedKontoId = ($row['vendor_konto_id'] === null || $row['vendor_konto_id'] === '') ? null : (int) $row['vendor_konto_id'];
                if ($fresh['kontoId'] !== $storedKontoId || $fresh['match'] !== $row['vendor_match']) {
                    db_modify(
                        "UPDATE pool_files SET " . poolVendorUpdateSql($fresh) . " WHERE id = " . (int) $row['id'],
                        __FILE__ . " line " . __LINE__
                    );
                }
                $vendor = $fresh;
            } else {
                $vendor = poolVendorFromRow($row, $vendorIndex);
            }
        } catch (Throwable $e) {
            // The vendor contract is a bonus on the file list; never let it break the list.
            error_log("_docPoolData vendor for {$row['filename']} failed: " . $e->getMessage() . " in " . $e->getFile() . ":" . $e->getLine());
            $vendor = null;
        }
    }

    $fil_nr++;
    
    // Build href - remove any existing poolFile from poolParams
    $cleanPoolParams = preg_replace('/&?poolFile=[^&]*/', '', $poolParams);
    $cleanPoolParams = ltrim($cleanPoolParams, '&');
    $hreftxt = "../includes/documents.php?$params&$cleanPoolParams&docFocus=$fil_nr&poolFile=" . urlencode($file);
    
    $data[] = [
        'filename' => $file,
        'subject' => $subject,
        'account' => $account,
        'amount' => $amount,
        'date' => $modDate,
        'href' => $hreftxt,
        'invoiceNumber' => $invoiceNumber,
        'description' => $description,
        'currency' => $currency,
        'vendor' => $vendor,
        'fil_nr' => $fil_nr,
        'version' => poolMetadataVersion($row),
        'manuallyEdited' => poolMetadataIsManual($row),
    ];
}

// MB-42: the customer's pool held the same bilag under two or three filenames, with identical
// fakturanr, amount and date, and nothing in the list said so. poolMarkDuplicates() groups those and
// sets duplicateOf on every member (see poolDuplicateMarker.php for why a hash cannot do this part).
$data = poolMarkDuplicates($data);

// Clear any previous output and send proper JSON
ob_end_clean();
header('Content-Type: application/json');

echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE);

exit;
