<?php
//                ___   _   _   ___  _     ___  _ _
//               / __| / \ | | |   \| |   |   \| / /
//               \__ \/ _ \| |_| |) | | _ | |) |  <
//               |___/_/ \_|___|___/|_||_||___/|_\_\
//
// --- includes/_docPoolData.php --- ver 5.0.0 --- 2026-10-07 ---
// LICENSE
//
// This program is free software. You can redistribute it and / or
// modify it under the terms of the GNU General Public License (GPL)
// which is published by The Free Software Foundation; either in version 2
// of this license or later version of your choice.
// However, respect the following:
//
// It is forbidden to use this program in competition with Saldi.DK ApS
// or other proprietor of the program without prior written agreement.
//
// The program is published with the hope that it will be beneficial,
// but WITHOUT ANY KIND OF CLAIM OR WARRANTY.
// See GNU General Public License for more details.
// http://www.saldi.dk/dok/GNU_GPL_v2.html
//
// Copyright (c) 2025-2026 Danosoft ApS
// ----------------------------------------------------------------------
// 20260914 CDX/LH Expose metadata versions and manual acceptance for document-pool editing.
// 20260922 CL/LAH Leverandørforslag fra AI-scan: every file now carries a 'vendor' object
//                  (see poolVendorMatcher.php / kravspec afsnit 5) or null, and files with
//                  vendor identity but no kreditor are matched again on every open (AI-6).
// 20260922 CL/LAH Vendor handling wrapped so it can never break the file list; invalid UTF-8
//                  from legacy rows is substituted instead of blanking the whole response.
// 20260925 LOE MB-42 Every row whose fakturanr, amount and date match another row's is marked
//                  duplicateOf, so the pool can show that the same bilag is in the list twice.
// 20261001 CL/NTR Merged the two history blocks into one and grouped the includes.
// 20261003 CL/SZ SD-717 Archived documents are left out of the list and the duplicate marking.
//                With archived=1 ("Vis arkiverede") only archived documents are returned, newest archive first, with their archive time.
// 20261003 CL/SZ SD-719 With limit: one page of the list as {rows, total, offset, limit, matches, extra, currentIndex}.
//                Search (q), sort (sort, order) and the match against the journal line (sum, dato) are done here over the full set (poolListQuery.php).
//                extra holds the open document (current) and the ticked ones (include[]) when they are not on the page; filesOnly=1 lists every file name.
//                toCurrent=1 extends the page down to the open document.
//                Without limit the whole list comes back as before.
// 20261007 CL/SZ SD-719 The list is built by poolListData() (docsIncludes/poolListData.php), which docPool.php also calls to send the first page with the page.

// Start output buffering FIRST to capture any output from includes
ob_start();

// Start session and set environment
@session_start();
$s_id = session_id();
$header = 'nix';  // Suppress header output
$bg = 'nix';      // Suppress body output
$title = 'docPoolData';

// Prevent caching of this JSON response to ensure fresh file list
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

// Include database connection and online.php to get $db
include_once(__DIR__ . "/connect.php");
include_once(__DIR__ . "/std_func.php");
include_once(__DIR__ . "/docsIncludes/poolVendorMatcher.php");
include_once(__DIR__ . "/docsIncludes/poolDuplicateMarker.php");
require_once __DIR__ . '/docsIncludes/poolMetadata.php';
require_once __DIR__ . '/docsIncludes/poolArchive.php';
require_once __DIR__ . '/docsIncludes/poolListQuery.php';
require_once __DIR__ . '/docsIncludes/poolListData.php';

// Get $db from session/online table
$qtxt = "select db from online where session_id = '$s_id' order by logtime desc limit 1";
$r = db_fetch_array(db_select($qtxt, __FILE__ . " line " . __LINE__));
$db = $r['db'] ?? '';

// Connect to the correct database
if ($db) {
    global $sqhost, $squser, $sqpass;
    $connection = db_connect($sqhost, $squser, $sqpass, $db, __FILE__ . " line " . __LINE__);
}

// Clean any output generated by includes
while (ob_get_level()) {
    ob_end_clean();
}
ob_start();

// SD-719: the list itself is built by poolListData(), which docPool.php also calls for the first page
$data = poolListData($_GET);

// Clear any previous output and send proper JSON
ob_end_clean();
header('Content-Type: application/json');

echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE);

exit;
